### ISSUE TITLE
refresh batt and date dont work

### ISSUE THREAD

**Issue by Lex132** [pigigaldi/Pock#106]
data of power battery (in percent) and time do not never update

**Comment by rapkyt** [comment]
In my case, it does update when I'm charging it, but not while being discharged.

**Comment by Lex132** [comment]
my case - does not update when charging and does not update while batt working

**Comment by Lex132** [comment]
update: if launch from Program folder - works fine! :)

**Comment by ashald** [comment]
I start Pock and it seems to work. But after my MBP goes to sleep and back it seems to be stuck and battery/calendar do not update until I restart Pock.

**Comment by kalongo** [comment]
My use case :
Setting : Hide Control Strip (Double press `control` key to toggle between Pock and System Touch Bar.)
Refresh works fine until I double press to go to system touch bar. When I go back to Pock's one, refresh doesn't work anymore.

**Comment by pigigaldi** [comment]
A fix for this issue is coming this weekend, thanks for all your inputs guys!

**Comment by pigigaldi** [comment]
Fixed in [v0.5.2](https://github.com/pigigaldi/Pock/tree/v0.5.2)

**Comment by kalongo** [comment]
Hi Pierluigi,

 

The issue is still the same for my use case :

With “Hide Control Strip” enabled, when I’m on Pock the Touch Bar, everything works fine.

When I double press “control” to go to OSX Touch Bar and then I come back to Pock some minutes later, the battery and the clock don’t refresh anymore.

 

Kalongo

 

De : Pierluigi Galdi <notifications@github.com>
Répondre à : pigigaldi/Pock <reply@reply.github.com>
Date : vendredi 28 juin 2019 à 13:18
À : pigigaldi/Pock <Pock@noreply.github.com>
Cc : Kalongo MULAMBA <kalongo@mulamba.com>, Comment <comment@noreply.github.com>
Objet : Re: [pigigaldi/Pock] refresh batt and date dont work (#106)

 

Fixed in v0.5.2

**Comment by onuruzun** [comment]
> Hi Pierluigi, The issue is still the same for my use case : With “Hide Control Strip” enabled, when I’m on Pock the Touch Bar, everything works fine. When I double press “control” to go to OSX Touch Bar and then I come back to Pock some minutes later, the battery and the clock don’t refresh anymore. Kalongo De : Pierluigi Galdi <notifications@github.com> Répondre à : pigigaldi/Pock <reply@reply.github.com> Date : vendredi 28 juin 2019 à 13:18 À : pigigaldi/Pock <Pock@noreply.github.com> Cc : Kalongo MULAMBA <kalongo@mulamba.com>, Comment <comment@noreply.github.com> Objet : Re: [pigigaldi/Pock] refresh batt and date dont work (#106) Fixed in v0.5.2 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

I think you need the close old Pock or delete maybe. And open the new version.

**Comment by kalongo** [comment]
Ok, let me try. I’ll keep you posted.

 

 

De : Onur Uzun <notifications@github.com>
Répondre à : pigigaldi/Pock <reply@reply.github.com>
Date : vendredi 28 juin 2019 à 13:45
À : pigigaldi/Pock <Pock@noreply.github.com>
Cc : Kalongo MULAMBA <kalongo@mulamba.com>, Comment <comment@noreply.github.com>
Objet : Re: [pigigaldi/Pock] refresh batt and date dont work (#106)

 

Hi Pierluigi, The issue is still the same for my use case : With “Hide Control Strip” enabled, when I’m on Pock the Touch Bar, everything works fine. When I double press “control” to go to OSX Touch Bar and then I come back to Pock some minutes later, the battery and the clock don’t refresh anymore. Kalongo De : Pierluigi Galdi notifications@github.com Répondre à : pigigaldi/Pock reply@reply.github.com Date : vendredi 28 juin 2019 à 13:18 À : pigigaldi/Pock Pock@noreply.github.com Cc : Kalongo MULAMBA kalongo@mulamba.com, Comment comment@noreply.github.com Objet : Re: [pigigaldi/Pock] refresh batt and date dont work (#106) Fixed in v0.5.2 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

I think you need the close old Pock or delete maybe. And open the new version.

**Comment by onuruzun** [comment]
Oh. I was tested the wrong case. I had same problem too.

**Comment by pigigaldi** [comment]
Thanks for the inputs. I think I'll need more time to investigate this situation better.
Let's move the discussion to #90 that is the first issue relative to this bug.
