### ISSUE TITLE
More cities in weather widget

### ISSUE THREAD

**Issue by mpl75** [pigigaldi/Pock#628]
hi, there is missing city "Brno" in Czech republic (it is second largest city in Czechia), can you add it please? 

Or, can I do it myself? I've found cities.csv in weather.pock package, but I can't find it on Github. And I do not now last column meaning…

**Comment by cshariq** [comment]
I have fixed this issue by implementing the bing maps api to fetch your current location and return your current city, neighbourhood or address any of which can be displayed. In addition it will have different icon options and you'll be able to see the 10 day weather by swiping. Currently working on a few bug though. I'll be done by the end of tomorrow and push a pull request to fix this. In addition i'll attach the .pock widget here once done so you can replace it with the existing weather widget as I know that pull requests can take some time to be implemented.

(Edit)
Here's the updated weather widget, just download by clicking download on the menubar and open it, it will automatically install and replace the existing weather widget in pock:
https://1drv.ms/f/s!Avh9vuHTyquQgdEJkt0NEVijldRXzQ?e=wtfRRY

Make sure you give pock location permissions because the weather widget now dynamically updates your location using the bing maps api instead of a preset.

**Comment by mpl75** [comment]
hi, new weather widget is still not part of standard installation. And, even I downloaded your pock file, I wasn't able to install it correctly.
Please, add some city to weather widget :-) Thank you.

**Comment by cshariq** [comment]
> hi, new weather widget is still not part of standard installation. And, even I downloaded your pock file, I wasn't able to install it correctly.
> Please, add some city to weather widget :-) Thank you.

@pigigaldi will have to add it to standard installation as for the issue with the installation, please provide me the error so I can see what the issue is.

**Comment by esetleges** [comment]
> I have fixed this issue by implementing the bing maps api to fetch your current location and return your current city, neighbourhood or address any of which can be displayed. In addition it will have different icon options and you'll be able to see the 10 day weather by swiping. Currently working on a few bug though. I'll be done by the end of tomorrow and push a pull request to fix this. In addition i'll attach the .pock widget here once done so you can replace it with the existing weather widget as I know that pull requests can take some time to be implemented.
> 
> (Edit) Here's the updated weather widget, just download by clicking download on the menubar and open it, it will automatically install and replace the existing weather widget in pock: https://1drv.ms/f/s!Avh9vuHTyquQgdEJkt0NEVijldRXzQ?e=wtfRRY
> 
> Make sure you give pock location permissions because the weather widget now dynamically updates your location using the bing maps api instead of a preset.

File not exist, may you upload again?

**Comment by cshariq** [comment]
> > I have fixed this issue by implementing the bing maps api to fetch your current location and return your current city, neighbourhood or address any of which can be displayed. In addition it will have different icon options and you'll be able to see the 10 day weather by swiping. Currently working on a few bug though. I'll be done by the end of tomorrow and push a pull request to fix this. In addition i'll attach the .pock widget here once done so you can replace it with the existing weather widget as I know that pull requests can take some time to be implemented.
> > (Edit) Here's the updated weather widget, just download by clicking download on the menubar and open it, it will automatically install and replace the existing weather widget in pock: https://1drv.ms/f/s!Avh9vuHTyquQgdEJkt0NEVijldRXzQ?e=wtfRRY
> > Make sure you give pock location permissions because the weather widget now dynamically updates your location using the bing maps api instead of a preset.
> 
> File not exist, may you upload again?

Sure, I can upload it again, but next time for the latest release you can go to [here](https://github.com/cshariq/weather-widget-1/releases/tag/%23UpdateRelease) and download Weather.pock.zip.

Here is the updated link as well (as far as I can see it works, if it doesn't for you just download it from my releases as [linked above](https://github.com/cshariq/weather-widget-1/releases/tag/%23UpdateRelease)):
https://1drv.ms/f/s!Avh9vuHTyquQgdEJuAyeGYjErKJ1uQ?e=4nlaOz

**Comment by Adithya-Bandara** [comment]
> > > I have fixed this issue by implementing the bing maps api to fetch your current location and return your current city, neighbourhood or address any of which can be displayed. In addition it will have different icon options and you'll be able to see the 10 day weather by swiping. Currently working on a few bug though. I'll be done by the end of tomorrow and push a pull request to fix this. In addition i'll attach the .pock widget here once done so you can replace it with the existing weather widget as I know that pull requests can take some time to be implemented.
> > > (Edit) Here's the updated weather widget, just download by clicking download on the menubar and open it, it will automatically install and replace the existing weather widget in pock: https://1drv.ms/f/s!Avh9vuHTyquQgdEJkt0NEVijldRXzQ?e=wtfRRY
> > > Make sure you give pock location permissions because the weather widget now dynamically updates your location using the bing maps api instead of a preset.
> > 
> > 
> > File not exist, may you upload again?
> 
> Sure, I can upload it again, but next time for the latest release you can go to [here](https://github.com/cshariq/weather-widget-1/releases/tag/%23UpdateRelease) and download Weather.pock.zip.
> 
> Here is the updated link as well (as far as I can see it works, if it doesn't for you just download it from my releases as [linked above](https://github.com/cshariq/weather-widget-1/releases/tag/%23UpdateRelease)): https://1drv.ms/f/s!Avh9vuHTyquQgdEJuAyeGYjErKJ1uQ?e=4nlaOz

Hello there, I recently installed your update weather widget. it installs well but in the widget it says like it is connecting with the weather app or something. so I removed it and re install the original one. But original one doesnt have my city, I'm in Sri Lanka. It lists ony few major cities. my city is "Anuradhapura" can you guide me to install the new widget and use it properly?

**Comment by cshariq** [comment]
Did you try restarting pock after installing the widget?

**Comment by Adithya-Bandara** [comment]
> Did you try restarting pock after installing the widget?

Yes, I did every possible thing, Tried restarting, and updating, restart macbook, reinstall pock and then reinstall the new widget. I couldnt  find a way to correct it.

**Comment by cshariq** [comment]
Try going into settings and manually give Pock permission to retrieve the location. This is probably the main cause of it being stuck at fetching data or whatever. It might not work immediately, you might have to restart Pock. You have to go to privacy --> location services(first thing on the latest version of mac os) --> turn on permission for Pock.

**Comment by Chinmaykanpara** [comment]
Hi , so i have replaced the old weather widget with the new one but its still stuck on fetching data , under the debug console this is what I get :

[Dock] Unsubscribe from observables and notifications…
[WeatherRepository]: init
[WeahterRepository]: Fetching data for current loaction
0
Unable to get location
[WeatherWidget]: Deinit
[WeatherRepository]: deinit
[Dock] Initialize DockWatcher
[Dock] Unsubscribe from observables and notifications…
[Dock] Subscribe to observables and notifications…
[WeahterRepository]: Fetching data for current loaction
0
Unable to get location

I have already given location permissions.
