### ISSUE TITLE
Status Widget isn't updating itself synchronously with the menu bar

### ISSUE THREAD

**Issue by onuruzun** [pigigaldi/Pock#90]
Hi,
first; I love this app. Thank you very much 😍
secondly; Status Widget (power item & datetime ) does not synchronously on Pock.

**Expected behavior**
Status Bar, power item and datetime should sync update with Menu Bar 🤔

**Screenshots**

_**Menu Bar:**_
<img width="292" alt="Ekran Resmi 2019-06-23 15 01 06" src="https://user-images.githubusercontent.com/21043314/59976040-d7057380-95c7-11e9-855c-b01affe0efb2.png">

Touch Bar:
<img width="1085" alt="Touch Bar Resmi 2019-06-23 15 01 12" src="https://user-images.githubusercontent.com/21043314/59976042-e1277200-95c7-11e9-9a8d-0da9dbb3b3c6.png">

**Comment by praveen-me** [comment]
And for fixing this I need to close and open Pock again every time.

**Comment by dfee** [comment]
I'm having this problem, too. And, the iTunes widget has stopped updating. It's currently just showing "Pock / iTunes" rather than "Song / Artist" as expected.

**Comment by iDjay** [comment]
same problem here :)

**Comment by ferodss** [comment]
For me, it keeps the status from the time I lock the screen and I have to restart the app

**Comment by ferodss** [comment]
> For me, it keeps the status from the time I lock the screen and I have to restart the app

Solved with v0.5.2 release

**Comment by onuruzun** [comment]
> > For me, it keeps the status from the time I lock the screen and I have to restart the app
> 
> Solved with v0.5.2 release

Check again after double press 'control' button

**Comment by iDjay** [comment]
Still not fixed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hvdklauw** [comment]
Can confirm, just updated to 0.5.2 and the time is 3 minutes behind.

Clicking hide control strip in the preferences twice does cause it to be updated.

**Comment by iDjay** [comment]
It‘s working sometimes and sometimes not 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by onuruzun** [comment]
> It‘s working sometimes and sometimes not
> 
> Sent with [GitHawk](http://githawk.com)

**Comment by MateuszDabrowski** [comment]
For me, it stopped on the Pock install time. Hiding/showing with double control, quitting and relaunching, locking and unlocking screen - nothing helps.

**Comment by alxdxx** [comment]
the time is clearly broken on the touchpad and cant sync (v 0.5.2)

**Comment by alanpearce** [comment]
The battery widget seems to work now, at least.
